"""
disease_data.py
-----------------------------------------------------
Shared disease knowledge base used by:
  - main.py (Flask app, rule-based + ML symptom diagnosis)
  - ml/generate_disease_dataset.py (synthetic training data generator)
  - ml/train_disease_symptom_model.py (RandomForest "AI" trainer)

Kept in its own module (no Flask / DB imports) so the ML training
scripts can import `disease_database` directly without needing a
running MySQL connection or the Flask app context.
"""

disease_database = [

{
    "crop":"Rice",
    "disease":"Brown Spot",
    "leaf_color":"Brown",
    "spot_color":"Brown",
    "spot_size":"Medium",
    "leaf_curl":"No",
    "powder":"No",
    "stem":"Healthy",
    "temperature":[20,35],
    "humidity":[70,100],
    "severity":"Medium",
    "cause":"Fungal Infection",
    "medicine":"Mancozeb",
    "dosage":"2 g/L",
    "spray":"Every 7 Days",
    "fertilizer":"Balanced NPK",
    "recovery":"10-15 Days",
    "yield_loss":"20%",
    "prevention":"Avoid standing water.",
    "medicine_image":"mancozeb.jpg",
    "disease_image":"brown_spot.jpg"
},

{
    "crop":"Rice",
    "disease":"Blast",
    "leaf_color":"Brown",
    "spot_color":"Black",
    "spot_size":"Large",
    "leaf_curl":"No",
    "powder":"No",
    "stem":"Healthy",
    "temperature":[22,30],
    "humidity":[80,100],
    "severity":"High",
    "cause":"Magnaporthe Fungus",
    "medicine":"Tricyclazole",
    "dosage":"0.6 g/L",
    "spray":"Every 10 Days",
    "fertilizer":"Potash Rich",
    "recovery":"15 Days",
    "yield_loss":"40%",
    "prevention":"Avoid excess nitrogen.",
    "medicine_image":"tricyclazole.jpg",
    "disease_image":"blast.jpg"
},

{
    "crop":"Tomato",
    "disease":"Early Blight",
    "leaf_color":"Brown",
    "spot_color":"Brown",
    "spot_size":"Medium",
    "leaf_curl":"No",
    "powder":"No",
    "stem":"Healthy",
    "temperature":[20,30],
    "humidity":[60,90],
    "severity":"Medium",
    "cause":"Alternaria Fungus",
    "medicine":"Mancozeb",
    "dosage":"2 g/L",
    "spray":"Weekly",
    "fertilizer":"Balanced NPK",
    "recovery":"10 Days",
    "yield_loss":"20%",
    "prevention":"Remove infected leaves.",
    "medicine_image":"mancozeb.jpg",
    "disease_image":"early_blight.jpg"
},

{
    "crop":"Tomato",
    "disease":"Late Blight",
    "leaf_color":"Black",
    "spot_color":"Black",
    "spot_size":"Large",
    "leaf_curl":"No",
    "powder":"Yes",
    "stem":"Healthy",
    "temperature":[15,25],
    "humidity":[80,100],
    "severity":"Critical",
    "cause":"Phytophthora",
    "medicine":"Metalaxyl",
    "dosage":"2 g/L",
    "spray":"Weekly",
    "fertilizer":"Balanced NPK",
    "recovery":"15 Days",
    "yield_loss":"50%",
    "prevention":"Avoid water on leaves.",
    "medicine_image":"metalaxyl.jpg",
    "disease_image":"late_blight.jpg"
},

{
    "crop":"Potato",
    "disease":"Late Blight",
    "leaf_color":"Black",
    "spot_color":"Black",
    "spot_size":"Large",
    "leaf_curl":"No",
    "powder":"Yes",
    "stem":"Healthy",
    "temperature":[15,25],
    "humidity":[80,100],
    "severity":"Critical",
    "cause":"Phytophthora infestans",
    "medicine":"Metalaxyl",
    "dosage":"2 g/L",
    "spray":"Weekly",
    "fertilizer":"Balanced NPK",
    "recovery":"15 Days",
    "yield_loss":"50%",
    "prevention":"Avoid excess irrigation.",
    "medicine_image":"metalaxyl.jpg",
    "disease_image":"late_blight.jpg"
},

{
    "crop":"Banana",
    "disease":"Panama Wilt",
    "leaf_color":"Yellow",
    "spot_color":"None",
    "spot_size":"None",
    "leaf_curl":"No",
    "powder":"No",
    "stem":"Rotten",
    "temperature":[25,35],
    "humidity":[60,90],
    "severity":"Critical",
    "cause":"Fusarium Fungus",
    "medicine":"Carbendazim",
    "dosage":"2 g/L",
    "spray":"Every 10 Days",
    "fertilizer":"Organic + NPK",
    "recovery":"20 Days",
    "yield_loss":"50%",
    "prevention":"Use healthy suckers.",
    "medicine_image":"carbendazim.jpg",
    "disease_image":"panama_wilt.jpg"
},

{
    "crop":"Apple",
    "disease":"Apple Scab",
    "leaf_color":"Green",
    "spot_color":"Brown",
    "spot_size":"Small",
    "leaf_curl":"No",
    "powder":"No",
    "stem":"Healthy",
    "temperature":[15,25],
    "humidity":[70,100],
    "severity":"Medium",
    "cause":"Venturia inaequalis Fungus",
    "medicine":"Captan",
    "dosage":"2 g/L",
    "spray":"Every 10 Days",
    "fertilizer":"Balanced NPK",
    "recovery":"15-20 Days",
    "yield_loss":"25%",
    "prevention":"Prune for airflow and remove fallen leaves.",
    "medicine_image":"captan.jpg",
    "disease_image":"apple_scab.jpg"
},

{
    "crop":"Wheat",
    "disease":"Rust",
    "leaf_color":"Yellow",
    "spot_color":"Brown",
    "spot_size":"Small",
    "leaf_curl":"No",
    "powder":"No",
    "stem":"Healthy",
    "temperature":[15,25],
    "humidity":[60,90],
    "severity":"High",
    "cause":"Puccinia Fungus",
    "medicine":"Hexaconazole",
    "dosage":"1 ml/L",
    "spray":"Every 10 Days",
    "fertilizer":"Balanced NPK",
    "recovery":"15 Days",
    "yield_loss":"30%",
    "prevention":"Use rust-resistant varieties.",
    "medicine_image":"hexaconazole.jpg",
    "disease_image":"rust.jpg"
},

{
    "crop":"Grapes",
    "disease":"Powdery Mildew",
    "leaf_color":"Green",
    "spot_color":"White",
    "spot_size":"Small",
    "leaf_curl":"No",
    "powder":"Yes",
    "stem":"Healthy",
    "temperature":[20,30],
    "humidity":[40,70],
    "severity":"Medium",
    "cause":"Erysiphe necator Fungus",
    "medicine":"Chlorothalonil",
    "dosage":"2 g/L",
    "spray":"Every 7 Days",
    "fertilizer":"Balanced NPK",
    "recovery":"10-15 Days",
    "yield_loss":"20%",
    "prevention":"Improve air circulation, avoid overhead watering.",
    "medicine_image":"chlorothalonil.jpg",
    "disease_image":"powdery_mildew.jpg"
},

{
    "crop":"Chilli",
    "disease":"Leaf Curl",
    "leaf_color":"Yellow",
    "spot_color":"None",
    "spot_size":"None",
    "leaf_curl":"Yes",
    "powder":"No",
    "stem":"Healthy",
    "temperature":[25,38],
    "humidity":[40,70],
    "severity":"High",
    "cause":"Begomovirus (whitefly-transmitted)",
    "medicine":"Imidacloprid",
    "dosage":"0.5 ml/L",
    "spray":"Every 10 Days",
    "fertilizer":"Balanced NPK",
    "recovery":"20-25 Days",
    "yield_loss":"35%",
    "prevention":"Control whitefly vectors, use virus-free seedlings.",
    "medicine_image":"imidacloprid.jpg",
    "disease_image":"leaf_curl.jpg"
},

{
    "crop":"General",
    "disease":"Healthy",
    "leaf_color":"Green",
    "spot_color":"None",
    "spot_size":"None",
    "leaf_curl":"No",
    "powder":"No",
    "stem":"Healthy",
    "temperature":[15,35],
    "humidity":[30,90],
    "severity":"None",
    "cause":"No disease detected",
    "medicine":"-",
    "dosage":"-",
    "spray":"-",
    "fertilizer":"Continue regular balanced fertilization",
    "recovery":"-",
    "yield_loss":"0%",
    "prevention":"Maintain good field hygiene and regular monitoring.",
    "medicine_image":"",
    "disease_image":"healthy.png"
}

]
